<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>mm-expenses-manager-common</artifactId>
        <groupId>mm-expenses-manager</groupId>
        <version>0.3.3-SNAPSHOT</version>
    </parent>

    <name>Expenses Manager Common Utils</name>
    <description>Expenses Manager common utils with utilities components.</description>

    <artifactId>common-utils</artifactId>
    <version>0.3.3-SNAPSHOT</version>

    <properties>
        <!-- Apache commons version -->
        <apache-commons-lang3-version>3.20.0</apache-commons-lang3-version>
        <apache-commons-collections4-version>4.5.0</apache-commons-collections4-version>
        <apache-commons-math3>3.6.1</apache-commons-math3>
        <apache-commons-validator-version>1.10.1</apache-commons-validator-version>
        <apache-commons-fileupload>2.0.0-M5</apache-commons-fileupload>
        <tools-jackson-core-version>3.1.2</tools-jackson-core-version>
        <jackson-datatype-jdk8-version>2.21.3</jackson-datatype-jdk8-version>
        <junit-platform-runner-version>1.14.4</junit-platform-runner-version>
    </properties>

    <dependencies>

        <!-- ExpensesManager dependencies -->
        <dependency>
            <groupId>mm-expenses-manager</groupId>
            <artifactId>common-exceptions</artifactId>
            <version>${mm-expenses-manager-common-exceptions-version}</version>
            <scope>compile</scope>
        </dependency>

        <!-- Apache commons dependencies -->
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
            <version>${apache-commons-collections4-version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${apache-commons-lang3-version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <version>${apache-commons-math3}</version>
        </dependency>

        <dependency>
            <groupId>commons-validator</groupId>
            <artifactId>commons-validator</artifactId>
            <version>${apache-commons-validator-version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-collections</artifactId>
                    <groupId>commons-collections</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-fileupload2-jakarta-servlet6</artifactId>
            <version>${apache-commons-fileupload}</version>
        </dependency>

        <!-- Jackson (JSON) dependencies -->
        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${tools-jackson-core-version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>tools.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${tools-jackson-core-version}</version>
            <scope>compile</scope>

            <!-- Because of GHSA-2m67-wjpj-xhg9 vulnerability that is fixed in jackson-core in 3.1.1 version, so here is a newer version in this pom too -->
            <exclusions>
                <exclusion>
                    <groupId>tools.jackson.core</groupId>
                    <artifactId>jackson-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jdk8</artifactId>
            <version>${jackson-datatype-jdk8-version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-runner</artifactId>
            <version>${junit-platform-runner-version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>pl.pragmatists</groupId>
            <artifactId>JUnitParams</artifactId>
            <version>${junit-params-version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.awaitility</groupId>
            <artifactId>awaitility</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>nl.jqno.equalsverifier</groupId>
            <artifactId>equalsverifier</artifactId>
            <scope>compile</scope>
        </dependency>

    </dependencies>

</project>