<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>mm-expenses-manager-common</artifactId>
        <groupId>mm-expenses-manager</groupId>
        <version>0.3.3-SNAPSHOT</version>
    </parent>

    <name>Expenses Manager Common PostgreSQL</name>
    <description>Expenses Manager common PostgreSQL module to work with PostgreSQL database.</description>

    <artifactId>common-postgresql</artifactId>
    <version>0.3.3-SNAPSHOT</version>

    <properties>
        <!-- PostgreSQL version -->
        <org-postgresql-version>42.7.11</org-postgresql-version>

        <!-- Hibernate dependencies -->
        <hibernate-orm-core-version>7.3.3.Final</hibernate-orm-core-version>
    </properties>

    <dependencies>

        <!-- ExpensesManager dependencies -->
        <dependency>
            <groupId>mm-expenses-manager</groupId>
            <artifactId>common-utils</artifactId>
            <version>${mm-expenses-manager-common-utils-version}</version>
            <scope>compile</scope>
        </dependency>

        <!-- Spring dependencies -->
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-commons</artifactId>
            <version>${spring-data-commons-version}</version>
        </dependency>

        <!-- PostgreSQL dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <version>${spring-boot-version}</version>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>${org-postgresql-version}</version>
        </dependency>

        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>${hibernate-orm-core-version}</version>
            <type>pom</type>
        </dependency>

        <!-- Liquibase dependencies -->
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>

        <!-- Other dependencies -->
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>bson</artifactId>
        </dependency>

    </dependencies>

</project>