app:
  configuration:
    name: @project.name@
    version: @project.version@
    port: 8185
    api:
      url: /api
    database:
      name: expenses-manager-finance
    scheduled-thread-pool-size: 100
  currency:
    default: app.currency.provider.nbp # path to default provider property
    default-provider: ${${app.currency.default}.name}
    default-currency: ${${app.currency.default}.details.default-currency}
    synchronization-cron: "0 * * * * *" # every 1 hour
    reschedule-when-synchronization-failed-cron: "*/15 * * * * *" # every 15 minutes
    clean-reschedule-cron: "*/5 * * * * *" # every 5 minutes
    provider:
      nbp:
        name: nbp
        client: npb-client
        url: http://api.nbp.pl/api/exchangerates
        details:
          data-format: json
          default-currency: PLN
          history-from-year: 2002
          max-months-to-fetch: 3
          max-days-to-fetch: 88

server:
  port: ${app.configuration.port}

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/${app.configuration.database.name}
      auto-index-creation: true
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

springdoc:
  swagger-ui:
    path: ${app.configuration.api.url}/ui
    disable-swagger-default-url: true
  api-docs:
    path: ${app.configuration.api.url}
