app:
  version: @project.version@
  name: @project.artifactId@
  port: 8185
  currency:
    default-currency: PLN
    default-provider: ${app.currency.provider.nbp.name}
    synchronization-cron: 0 0 13 ? * * #everyday at 13:00
    provider:
      nbp:
        name: nbp-provider
        client: npb-client
        url: http://api.nbp.pl/api/exchangerates
        details:
          data-format: json
          default-currency: PLN
          history-from-year: 2002
          max-months-to-fetch: 3

server:
  port: ${app.port}

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/expenses-manager-finance
      auto-index-creation: true
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

springdoc:
  swagger-ui:
    path: /api/ui
    disable-swagger-default-url: true
  api-docs:
    path: /api
