app:
  configuration:
    name: @project.name@
    version: @project.version@
    description: @project.description@
    contact:
      name: @developer-name@
      email: @developer-email@
      role: @developer-role@
    port: 8185
    api:
      url: /api
    database:
      name: expenses-manager-finance
    scheduled-thread-pool-size: 100
    cache:
      type: map # 'map' or 'redis'
      clear-cron: "*/5 * * * * *" # every 1h
  currency:
    default: app.currency.provider.nbp # path to default provider property
    default-provider: ${${app.currency.default}.name}
    default-currency: PLN
    synchronization-cron: "0 * * * * *" # every 1 hour
    reschedule-when-synchronization-failed-cron: "*/15 * * * * *" # every 15 minutes
    clean-reschedule-cron: "*/5 * * * * *" # every 5 minutes
    provider:
      nbp:
        name: nbp
        client: npb-client
        url: http://api.nbp.pl/api/exchangerates
        details:
          data-format: json
          history-from-year: 2002
          max-days-to-fetch: 90
  kafka:
    enabled: true
    brokers: localhost:9092
    type: kafka
    username: kafka
    password: kafka

server:
  port: ${app.configuration.port}

spring:
  application:
    name: ${app.configuration.name}
  profiles:
    active: dev
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/${app.configuration.database.name}
      auto-index-creation: true
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${app.kafka.brokers}
      binders:
        kafka:
          type: ${app.kafka.type}

springdoc:
  swagger-ui:
    path: ${app.configuration.api.url}/ui
    disable-swagger-default-url: true
  api-docs:
    path: ${app.configuration.api.url}
