app:
  configuration:
    name: @project.name@
    version: @project.version@
    description: @project.description@
    active-profile: @active-profile@
    port: 8181
    contact:
      name: @developer-name@
      email: @developer-email@
      role: @developer-role@
    api:
      url: /api
      ui-url: ${app.configuration.api.url}/ui
      disable-default-url: true
    database:
      mongodb:
        user: admin
        password: gP_h3cS!Lqu-4
        name: expenses-manager-order
        host: localhost
        port: 27017
        uri: mongodb://${app.configuration.database.mongodb.user}:${app.configuration.database.mongodb.password}@${app.configuration.database.mongodb.host}:${app.configuration.database.mongodb.port}/${app.configuration.database.mongodb.name}?authSource=admin
    pagination:
      min-page-number: 0
      default-page-size: 10
      max-page-size: 50

server:
  port: ${app.configuration.port}

spring:
  application:
    name: ${app.configuration.name}
  profiles:
    active: ${app.configuration.active-profile}
  data:
    mongodb:
      uri: ${app.configuration.database.mongodb.uri}
      auto-index-creation: true
    web:
      pageable:
        default-page-size: ${app.configuration.pagination.default-page-size}
        max-page-size: ${app.configuration.pagination.max-page-size}

springdoc:
  swagger-ui:
    path: ${app.configuration.api.ui-url}
    disable-swagger-default-url: ${app.configuration.api.disable-default-url}
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: ${app.configuration.api.url}