openapi: 3.0.1
info:
  title: order-schema
  version: latest

servers:
  - url: http://localhost:8190

tags:
  - name: Order
    description: Provide API for orders management.

paths:

  /orders:
    get:
      tags:
        - Order
      summary: Finds all available orders with additional filters.
      description: Check for all available orders based on additional filtering options if needed.
      operationId: findAll
      parameters:
        - name: pageNumber
          in: query
          required: false
          example: 0
          schema:
            type: integer
            default: 0
            minimum: 0
            format: int32
        - name: pageSize
          in: query
          required: false
          example: 15
          schema:
            type: integer
            default: 10
            minimum: 1
            format: int32
        - name: sort
          in: query
          required: false
          description: Sort orders by.
          schema:
            $ref: "#/components/schemas/SortOrderRequest"
        - name: isDeleted
          in: query
          required: false
          description: If true then retrieves orders even if they are deleted, false means to retrieve not deleted orders. By default all orders will be returned.
          schema:
            type: boolean
        - name: shouldConvertCurrency
          in: query
          required: false
          description: Defines if prices currencies of ordered products and the final price of order should be converted to the default currency. By default it will not be converted.
          schema:
            type: boolean
            default: false
        - name: name
          in: query
          required: false
          description: Specific name of the product.
          schema:
            type: string
            minLength: 1
            maxLength: 200
        - name: nameOperation
          in: query
          required: false
          description: Expected operation for name if present.
          schema:
            allOf:
              - $ref: "#/components/schemas/TextOperationRequest"
              - default: equal
        - name: productsCount
          in: query
          required: false
          description: Specifies how many ordered products are available for the order.
          schema:
            type: integer
            format: int32
        - name: productsCountOperation
          in: query
          required: false
          description: Expected operation for products count if present.
          schema:
            allOf:
              - $ref: "#/components/schemas/NumberOperationRequest"
              - default: greaterThanOrEqual
        - name: query
          in: query
          required: false
          description: Explicitly defined query to filter orders result based on the orders specification criteria.
          schema:
            type: string

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderPage"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorMessage"

    post:
      tags:
        - Order
      summary: Creates a new order.
      description: Create a new order.
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateNewOrderRequest"
      parameters:
        - name: shouldConvertCurrency
          in: query
          required: false
          description: Defines if prices currencies of ordered products and the final price of order should be converted to the default currency. By default it will not be converted.
          schema:
            type: boolean
            default: false

      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorMessage"

  /orders/{id}:
    get:
      tags:
        - Order
      summary: Finds order by id.
      description: Find order by given id.
      operationId: findById
      parameters:
        - name: id
          in: path
          description: Order id.
          required: true
          schema:
            type: string
            format: uuid
        - name: isDeleted
          in: query
          required: false
          description: If true then retrieves orders even if they are deleted, false means to retrieve not deleted orders. By default all orders will be returned.
          schema:
            type: boolean
            default: false
        - name: shouldConvertCurrency
          in: query
          required: false
          description: Defines if prices currencies of ordered products and the final price of order should be converted to the default currency. By default it will not be converted.
          schema:
            type: boolean
            default: false

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorMessage"

    patch:
      tags:
        - Order
      summary: Update an order.
      description: Update an order.
      operationId: update
      parameters:
        - name: id
          in: path
          description: Order id.
          required: true
          schema:
            type: string
            format: uuid
        - name: shouldConvertCurrency
          in: query
          required: false
          description: Defines if prices currencies of ordered products and the final price of order should be converted to the default currency. By default it will not be converted.
          schema:
            type: boolean
            default: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderRequest"

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorMessage"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorMessage"

    delete:
      tags:
        - Order
      summary: Delete an order.
      description: Remove an order by given id.
      operationId: deleteById
      parameters:
        - name: id
          in: path
          description: Order id.
          required: true
          schema:
            type: string
            format: uuid

      responses:
        "204":
          description: OK
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorMessage"

  /orders/remove:
    delete:
      tags:
        - Order
      summary: Delete orders by ids.
      description: Remove orders by given ids.
      operationId: deleteByIds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderIds"

      responses:
        "204":
          description: OK
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiErrorMessage"

components:
  schemas:

    ApiErrorMessage:
      required:
        - message
      type: object
      properties:
        code:
          type: string
          description: API error code.
        status:
          type: string
          description: HTTP status.
        message:
          type: string
          description: Error message.
        occurredAt:
          type: string
          description: Date when error occurred.
      description: API error message details.

    OrderIds:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          description: Orders ids.
          items:
            type: string
            format: uuid
      additionalProperties: false
      description: Request with ids of orders.

    SortOrderRequest:
      type: string
      enum: [ NAME_ASC, NAME_DESC, CREATED_AT_ASC, CREATED_AT_DESC, LAST_MODIFIED_AT_ASC, LAST_MODIFIED_AT_DESC ]
      x-enum-varnames: [ NAME_ASC, NAME_DESC, CREATED_AT_ASC, CREATED_AT_DESC, LAST_MODIFIED_AT_ASC, LAST_MODIFIED_AT_DESC ]
      description: Sorting order for orders.

    TextOperationRequest:
      type: string
      enum: [ isNull, equal, notEqual, startsWith, endsWith, contains ]
      x-enum-varnames: [ isNull, equal, notEqual, startsWith, endsWith, contains ]
      description: Possible text operation types for specific query parameter.

    NumberOperationRequest:
      type: string
      enum: [ isNull, equal, notEqual, lessThan, lessThanOrEqual, greaterThan, greaterThanOrEqual ]
      x-enum-varnames: [ isNull, equal, notEqual, lessThan, lessThanOrEqual, greaterThan, greaterThanOrEqual ]
      description: Possible number operation types for specific query parameter.

    CreateNewOrderedProductRequest:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: string
          format: uuid
          description: ID of the product that is expected to be ordered.
        quantity:
          type: double
          minimum: 0
          description: Ordered product quantity.
        price:
          $ref: '#/components/schemas/PriceRequest'
      additionalProperties: false
      description: New ordered product request data.

    CreateNewOrderRequest:
      type: object
      required:
        - name
        - orderedProducts
      properties:
        name:
          type: string
          description: The name of the order.
        orderedProducts:
          type: array
          description: Products in the order.
          items:
            $ref: '#/components/schemas/CreateNewOrderedProductRequest'
      additionalProperties: false
      description: New order request data.

    UpdateOrderedProductRequest:
      type: object
      required:
        - orderedProductId
      properties:
        orderedProductId:
          type: string
          format: uuid
          description: Ordered product id.
        quantity:
          type: double
          description: Ordered product quantity.
        price:
          $ref: '#/components/schemas/PriceRequest'
      additionalProperties: false
      description: Ordered product to be updated request data.

    UpdateOrderRequest:
      type: object
      properties:
        name:
          type: string
          description: The name of the order.
        orderedProducts:
          type: array
          description: Already available products in the order to be updated.
          items:
            $ref: '#/components/schemas/UpdateOrderedProductRequest'
        newProducts:
          type: array
          description: New products to be added to the order.
          items:
            $ref: '#/components/schemas/CreateNewOrderedProductRequest'
        removeProducts:
          type: array
          description: Products to be removed from the order.
          items:
            type: string
            format: uuid
      additionalProperties: false
      description: Order to be updated request data.

    PriceRequest:
      type: object
      required:
        - currency
        - value
      properties:
        currency:
          type: string
          description: Currency code of the price.
        value:
          type: BigDecimal
          minimum: 0
          description: Price value.
      additionalProperties: false
      description: Price request data.

    PriceResponse:
      type: object
      properties:
        currency:
          type: string
          description: Currency code of the price.
        amount:
          type: BigDecimal
          description: Price value.
        isOriginal:
          type: boolean
          description: Defines if it is original price or modified on demand.
      additionalProperties: false
      description: Price response data.
      example: |
        {"currency": "PLN", "amount": 1.15, "isOriginal": true}

    MultiPricesResponse:
      type: array
      items:
        $ref: '#/components/schemas/PriceResponse'
      description: Price response data distinguished by currency.
      example: |
        [{"currency": "PLN", "amount": 2.30}, {"currency": "EUR", "amount": 7.14}]

    OrderedProductResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Ordered product id.
        productId:
          type: string
          format: uuid
          description: Direct id of the ordered product.
        quantity:
          type: double
          description: Ordered product quantity.
        price:
          $ref: '#/components/schemas/MultiPricesResponse'
          description: Product price when it has been bought.
        priceSummary:
          $ref: '#/components/schemas/MultiPricesResponse'
          description: Summary price for all related products.
        createdAt:
          type: string
          description: Date when ordered product has been created.
        lastModifiedAt:
          type: string
          description: Date when ordered product has been modified.
      additionalProperties: false
      description: Ordered product response data.

    OrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Order id.
        name:
          type: string
          description: Order name.
        createdAt:
          type: string
          description: Date when order has been created.
        lastModifiedAt:
          type: string
          description: Date when order has been modified.
        priceSummary:
          $ref: '#/components/schemas/MultiPricesResponse'
          description: Order summary price for all products.
        orderedProducts:
          type: array
          description: Products in the order.
          items:
            $ref: '#/components/schemas/OrderedProductResponse'
      additionalProperties: false
      description: Order response data.

    OrderPage:
      type: object
      required:
        - content
        - empty
        - first
        - last
        - page
        - size
        - hasNext
        - pages
        - elements
        - total
      properties:
        content:
          type: array
          description: Orders content on page.
          items:
            $ref: '#/components/schemas/OrderResponse'
        empty:
          type: boolean
          description: Defines if the page has empty content.
        first:
          type: boolean
          description: Defines if retrieved page is first.
        last:
          type: boolean
          description: Defines if retrieved page is last.
        page:
          type: integer
          description: Orders page number.
          format: int32
          minimum: 0
        size:
          type: integer
          description: Orders page size.
          format: int32
          minimum: 1
        hasNext:
          type: boolean
          description: Defines if there is more available pages.
        totalPages:
          type: integer
          description: Total available pages of orders.
          format: int32
        elements:
          type: integer
          description: Number of elements on page.
          format: int32
        totalElements:
          type: integer
          description: Total available orders.
          format: int64
      description: Page with orders data.
