<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>mm-expenses-manager-finance</artifactId>
        <groupId>mm-expenses-manager</groupId>
        <version>0.2.9-SNAPSHOT</version>
    </parent>

    <name>Expenses Manager Finance App</name>
    <description>Finance service that handles the whole behaviour of the financial operations.</description>

    <packaging>jar</packaging>

    <artifactId>mm-expenses-manager-finance-app</artifactId>
    <version>0.2.9-SNAPSHOT</version>

    <dependencies>
        <!-- ExpensesManager dependencies -->
        <dependency>
            <groupId>mm-expenses-manager</groupId>
            <artifactId>mm-expenses-manager-finance-api</artifactId>
            <version>${mm-expenses-manager-finance-api-version}</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>${app-resource-directory}</directory>
                <filtering>true</filtering>
                <includes>
                    <include>${app-resource-include-yml}</include>
                </includes>
            </resource>
        </resources>

        <plugins>
            <!-- Maven plugins -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>resources</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>resources</goal>
                        </goals>
                        <configuration>
                            <delimiters>
                                <delimiter>${properties-delimiter}</delimiter>
                            </delimiters>
                            <useDefaultDelimiters>false</useDefaultDelimiters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>${spring-boot-version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok-version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct-version}</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok-mapstruct-binding</artifactId>
                            <version>${lombok-mapstruct-binding-version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <showWarnings>true</showWarnings>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <reuseForks>true</reuseForks>
                    <forkCount>2</forkCount>
                    <excludes>
                        <exclude>mm/expenses/manager/finance/exchangerate/ExchangeRateMapperImpl.class</exclude>
                        <exclude>mm/expenses/manager/finance/cache/exchangerate/ExchangeRateCacheMapperImpl.class
                        </exclude>
                        <exclude>mm/expenses/manager/finance/converter/CurrencyConverterMapperImpl.class</exclude>
                    </excludes>
                </configuration>
            </plugin>

            <!-- Spring plugins -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Jacoco plugins -->
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-version}</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <excludes>
                        <exclude>mm/expenses/manager/finance/exchangerate/ExchangeRateMapperImpl.class</exclude>
                        <exclude>mm/expenses/manager/finance/cache/exchangerate/ExchangeRateCacheMapperImpl.class
                        </exclude>
                        <exclude>mm/expenses/manager/finance/converter/CurrencyConverterMapperImpl.class</exclude>
                    </excludes>
                    <rules>
                        <rule>
                            <limits>
                                <limit>
                                    <counter>INSTRUCTION</counter>
                                    <minimum>${app-jacoco-coverage-minimum}</minimum>
                                </limit>
                            </limits>
                        </rule>
                    </rules>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>